name: Deploy to SiteGround
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Keeping your path exactly as you had it
          server-dir: cv.bioszolventa.com/public_html/ruben_bmw/
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          local-dir: ./dist/
          dangerous-clean-slate: true

      #- name: 🧹 Flush SiteGround Cache
        #uses: appleboy/ssh-action@master
        #with:
          #host: ${{ secrets.FTP_SERVER }}
          #username: ${{ secrets.SSH_USERNAME }}
          #key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 👇 THIS IS THE NEW PART FOR THE PASSWORD
          #passphrase: ${{ secrets.SSH_PASSPHRASE }}
          #port: 18765
          #script: site-tools-client domain:flush-cache cv.bioszolventa.com


